webtalk_init -webtalk_dir C:/Users/ASUS/Documents/CESE/CLP/Practicas/ALU_4b/ALU_4b.sim/sim_1/behav/xsim/xsim.dir/uart_alu_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  8 21:19:38 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b428cf19-c93d-4b9f-897a-19d14549d350" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "455d6e598b5443d7b62f0f1dc17dd8e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "861 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12736_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3514210338 -regid "" -xml C:/Users/ASUS/Documents/CESE/CLP/Practicas/ALU_4b/ALU_4b.sim/sim_1/behav/xsim/xsim.dir/uart_alu_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ASUS/Documents/CESE/CLP/Practicas/ALU_4b/ALU_4b.sim/sim_1/behav/xsim/xsim.dir/uart_alu_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ASUS/Documents/CESE/CLP/Practicas/ALU_4b/ALU_4b.sim/sim_1/behav/xsim/xsim.dir/uart_alu_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
